export const PAGES = [
 {path:'/how-it-works/',title:'How the Sunset Forecast Works',description:'Understand Skying’s sunset-quality score, weather inputs, golden-hour calculations and forecast limitations.',body:`
 <p>Skying is a small sunset-planning tool built by Gaurav Sharma. It combines a weather forecast with a transparent scoring rule to help you decide when to look at the sky. The score has not been calibrated against a dataset of observed sunset photographs.</p>
 <h2>What goes into the score?</h2>
 <p>Skying reads hourly cloud cover at low, middle and high levels, visibility, precipitation probability and relative humidity from <a href="https://open-meteo.com/en/docs">Open-Meteo</a>. It averages available observations within 90 minutes of sunset, giving more weight to times closer to sunset.</p>
 <ul><li><strong>34% upper-cloud suitability:</strong> a blend of 72% high and 28% middle cloud, with the highest suitability between 30% and 70% cover.</li><li><strong>30% horizon conditions:</strong> a penalty for low cloud and very heavy total cloud. This is a weather-based estimate, not a map of buildings or hills.</li><li><strong>14% visibility:</strong> clearer air receives a higher score.</li><li><strong>12% rain conditions:</strong> lower precipitation probability receives a higher score.</li><li><strong>10% humidity:</strong> lower near-surface relative humidity receives a higher score in this heuristic.</li></ul>
 <p>Very heavy total cloud or an almost cloudless sky receives a further 12-point reduction. The result is rounded and limited to 0–100. Missing required weather data produces an unavailable score, not an invented value.</p>
 <h2>How to read the number</h2>
 <p>90–100 is Exceptional, 78–89 Excellent, 63–77 Good, 45–62 Average and below 45 Poor. These are Skying’s descriptive categories. A score of 80 does not mean an 80% chance of a colourful sunset.</p>
 <h2>Dates, daylight and freshness</h2>
 <p>Sunset times come from Open-Meteo. Golden hour is calculated using <a href="https://github.com/mourner/suncalc">SunCalc</a>, from +6° to −4° solar altitude; blue hour runs from −4° to −6°. Definitions vary between photographers. These estimates do not model your exact horizon, refraction or terrain.</p>
 <p>Each page shows its location’s timezone and the time Skying retrieved the weather data. This retrieval time is not the weather model’s issuance time. Forecasts can be reused for 30 minutes. If a refresh fails, a saved forecast may be shown for up to six hours, only on the same local day, with a clear warning. Cached data is best-effort and may not be available everywhere.</p>
 <h2>What the forecast cannot promise</h2>
 <p>Skying does not directly model aerosol colour, smoke, the view toward the distant horizon or the beauty of a photograph. Longer-range cloud predictions may change. Use the seven-day outlook for planning, check again near the time, and observe actual conditions. At high latitudes, a sunset or complete light interval may not occur on a particular day.</p>
 <p>Location search uses Photon and <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>. Curated cities use fixed city-centre coordinates; a precise-location forecast uses the coordinates you request. <a href="https://github.com/gauravsharma2003/skying">Inspect the source and scoring rules on GitHub</a>.</p>`},
 {path:'/guides/golden-hour/',title:'Sunset Time, Golden Hour and Blue Hour',description:'See how sunset time differs from golden hour and blue hour, and how Skying calculates local photography windows.',body:`
 <p>Sunset is one event. Golden hour and blue hour describe longer intervals around it. None of these times alone tells you how colourful the sky will be.</p>
 <h2>Golden hour is not always sixty minutes</h2>
 <p>Skying defines evening golden hour as the sun moving from 6° above the horizon to 4° below it. Its duration changes with latitude and season. Each forecast calculates those crossings for the selected coordinates and displays them in local time.</p>
 <h2>Blue hour follows</h2>
 <p>Our blue-hour interval uses solar altitude from −4° to −6°. Cloud cover, terrain and artificial light affect what the scene looks like. At high latitudes, the sun may not cross both limits: the page will say “No complete interval” rather than show a made-up time.</p>
 <h2>A practical plan</h2>
 <p>Use the calculated window to decide when to arrive, then use the quality score and cloud forecast to decide how promising the evening looks. Check the local date and timezone before making plans across time zones.</p>
 <p>Times are estimates for an ideal horizon. The <a href="https://gml.noaa.gov/grad/solcalc/calcdetails.html">NOAA solar-calculation notes</a> explain why atmospheric conditions can affect observed solar events. Skying uses <a href="https://github.com/mourner/suncalc">SunCalc</a> for its light intervals.</p>`},
 {path:'/guides/sunset-clouds/',title:'What Clouds Mean for Sunset Colour',description:'Read Skying’s cloud-layer indicators and understand why cloud amount alone cannot predict a colourful sunset.',body:`
 <p>A single cloud-cover percentage hides an important distinction: clouds can provide a surface for warm evening light, or block your view of it.</p>
 <h2>Read the layers together</h2>
 <p>In Skying’s model, moderate upper-cloud cover improves the colour-canvas component. Heavy low cloud reduces the horizon component. A high-cloud reading alone does not override poor visibility or rain conditions.</p>
 <h2>Clear is different from colourful</h2>
 <p>A clear sky can offer an unobstructed sunset even when our model gives it a modest colour score. The tool is tuned to its own interpretation of colourful conditions, not every style of landscape photography.</p>
 <h2>Use the explanation, not only the score</h2>
 <p>Look at the high-cloud and low-cloud cards alongside visibility and rain chance. Two evenings with a similar score can have very different conditions. Check the actual sky before committing to a view: weather near the horizon may differ from a forecast grid cell.</p>
 <p>These are explanations of <a href="/how-it-works/">Skying’s heuristic</a>, not universal meteorological thresholds or measured accuracy claims.</p>`},
 {path:'/guides/forecast-confidence/',title:'How Far Ahead Can You Plan a Sunset?',description:'Use Skying’s seven-day sunset outlook while accounting for changing weather, forecast freshness and local conditions.',body:`
 <p>The seven-day outlook helps identify evenings to watch. It should not be treated as seven equally certain predictions.</p>
 <h2>Plan broadly, check again later</h2>
 <p>Use later dates to compare possible outings. Revisit the forecast on the day and near sunset, when your own observations can add context. A changed score means the inputs have changed; it is not a record of an observed sunset.</p>
 <h2>Check the timestamp</h2>
 <p>The page reports when Skying retrieved weather data. A saved-forecast warning means the latest refresh failed and the displayed data is older. Skying does not keep showing yesterday’s forecast as today’s.</p>
 <h2>There is no calibrated probability here</h2>
 <p>Skying uses a weighted rule, not a validated probability model. A higher number means the forecast inputs fit that rule better. We do not publish an accuracy percentage because we have not measured one against a representative observation dataset.</p>
 <p><a href="/how-it-works/">Read the inputs, weights and limitations</a>, then <a href="/sunset-forecast/">choose a city</a>.</p>`},
 {path:'/about/',title:'About Skying',description:'Skying is an open-source sunset-planning tool by Gaurav Sharma, combining weather forecasts and local photography times.',body:`<p>Skying helps answer a small question: is this evening’s sunset worth making time for?</p><p>Built by Gaurav Sharma, it combines Open-Meteo weather data, location search and astronomical light windows in a free browser tool. No account is required to view a forecast.</p><p>The source is public at <a href="https://github.com/gauravsharma2003/skying">gauravsharma2003/skying</a>. You can report a reproducible issue there. Read <a href="/how-it-works/">how the scoring works</a> before interpreting a number as a promise.</p>`},
 {path:'/privacy/',title:'Location and Privacy',description:'Learn how Skying handles location searches, optional device location and external services.',body:`<p>Skying does not require an account. Curated city pages use fixed city-centre coordinates.</p><h2>Location search</h2><p>Typed searches are sent to Photon, an OpenStreetMap-backed search service. The homepage may use ipapi.co to suggest an approximate city based on your public IP address. That service receives the network information needed to answer the request.</p><h2>Device location is optional</h2><p>Skying requests browser location permission only when you choose a location button. Coordinates may be sent to Photon to label the place and to Skying’s server and Open-Meteo to produce a forecast. A custom forecast URL includes rounded coordinates and the location label. Anyone you share that URL with can read them; use a curated city link if you prefer not to share a precise location.</p><h2>Hosting and external services</h2><p>Cloudflare hosts the site and may process request logs. The application does not add advertising trackers or a client analytics SDK. External services apply their own policies: <a href="https://open-meteo.com/en/terms">Open-Meteo</a>, <a href="https://ipapi.co/privacy/">ipapi.co</a> and <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare</a>.</p>`}
];
